# Generated by Django 3.2.11 on 2022-03-15 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('describtion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('non_fungible_token', models.TextField(unique=True)),
                ('path', models.CharField(max_length=200)),
                ('heeght', models.FloatField()),
                ('width', models.FloatField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.gallery')),
            ],
        ),
    ]
