# Generated by Django 3.2.11 on 2022-03-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='describtion',
            new_name='description',
        ),
    ]
